import { AICompanyAgent } from "./types";

export const aiCompanyAgents: AICompanyAgent[] = [
  {
    id: "executive-controller",
    name: "AI Executive Controller",
    department: "executive",
    mission: "Tổng hợp sức khỏe toàn bộ các mảng liên kết đối tác, ưu tiên vấn đề và đưa các quyết định cần chủ doanh nghiệp phê duyệt.",
    inputs: ["business unit health", "P&L", "cashflow", "inventory", "channel performance", "risk alerts"],
    outputs: ["executive brief", "portfolio priorities", "approval queue", "scale/hold/kill recommendation"],
    kpis: [
      { key: "net_margin", label: "Biên lợi nhuận ròng", direction: "maximize", unit: "%" },
      { key: "roic", label: "ROIC", direction: "maximize", unit: "%" },
      { key: "critical_alert_latency", label: "Độ trễ cảnh báo nghiêm trọng", direction: "minimize", unit: "days" },
    ],
    allowedActions: ["rank_business_units", "request_analysis", "create_approval_request"],
    approvalRequiredFor: ["move_cash", "sign_contract", "scale_campaign"],
    riskLevel: "critical",
  },
  {
    id: "business-unit-controller",
    name: "AI Business Unit Controller",
    department: "analytics",
    mission: "Theo dõi end-to-end từng mảng kinh doanh, phát hiện điểm nghẽn giữa marketing, bán hàng, vận hành và tài chính.",
    inputs: ["Pancake", "Pancake POS", "Pancake CRM", "Botcake", "orders", "inventory", "finance", "channel metrics"],
    outputs: ["business unit health", "bottleneck analysis", "early warnings", "daily operating brief"],
    kpis: [
      { key: "bottleneck_detection", label: "Độ chính xác phát hiện điểm nghẽn", direction: "maximize", unit: "%" },
      { key: "warning_lead_time", label: "Thời gian cảnh báo sớm", direction: "maximize", unit: "days" },
    ],
    allowedActions: ["query_metrics", "flag_bottleneck", "generate_business_unit_brief"],
    approvalRequiredFor: [],
    riskLevel: "low",
  },
  {
    id: "product-strategist",
    name: "AI Product Strategist",
    department: "product",
    mission: "Theo dõi hiệu quả SKU, giá bán và offer dựa trên unit economics thực tế của từng mảng.",
    inputs: ["product cost", "orders", "returns", "gross margin", "channel performance"],
    outputs: ["SKU score", "pricing recommendation", "offer recommendation", "test recommendation"],
    kpis: [
      { key: "contribution_margin", label: "Contribution margin", direction: "maximize", unit: "%" },
      { key: "sku_profit", label: "Lợi nhuận theo SKU", direction: "maximize", unit: "VND" },
    ],
    allowedActions: ["recommend_price", "score_sku", "recommend_offer"],
    approvalRequiredFor: ["change_price", "launch_campaign"],
    riskLevel: "high",
  },
  {
    id: "brand-director",
    name: "AI Brand Director",
    department: "brand",
    mission: "Đánh giá hiệu quả thông điệp, creative và định vị dựa trên dữ liệu quảng cáo và chuyển đổi thực tế.",
    inputs: ["brand strategy", "creative library", "ad metrics", "conversion by creative", "customer feedback"],
    outputs: ["creative diagnosis", "creative briefs", "content angles", "brand consistency alerts"],
    kpis: [
      { key: "creative_win_rate", label: "Tỷ lệ creative thắng", direction: "maximize", unit: "%" },
      { key: "creative_fatigue_rate", label: "Tỷ lệ creative mệt", direction: "minimize", unit: "%" },
    ],
    allowedActions: ["generate_brief", "score_creative", "flag_creative_fatigue"],
    approvalRequiredFor: ["publish_sensitive_claim"],
    riskLevel: "medium",
  },
  {
    id: "channel-ads-performance-manager",
    name: "AI Channel & Ads Performance Manager",
    department: "channels",
    mission: "Quản lý toàn bộ chỉ số các kênh thương mại và quảng cáo; đồng bộ trực tiếp dữ liệu Ads từ Pancake, đối chiếu với đơn hàng/doanh thu và đưa đề xuất phân bổ ngân sách, kênh, campaign, ad set và creative.",
    inputs: [
      "Pancake Ads Manager: ad accounts",
      "Pancake Ads Manager: campaigns",
      "Pancake Ads Manager: ad sets",
      "Pancake Ads Manager: ads",
      "Pancake POS orders",
      "Pancake POS revenue",
      "Pancake POS returns",
      "Pancake marketplace channels",
      "inventory",
      "business unit targets"
    ],
    outputs: [
      "channel scorecard",
      "CAC/CPA/ROAS/MER analysis",
      "budget allocation recommendation",
      "campaign/ad set/ad ranking",
      "creative fatigue alert",
      "channel anomaly alert",
      "scale/hold/kill proposal"
    ],
    kpis: [
      { key: "cac_delivered", label: "CAC đơn giao thành công", direction: "minimize", unit: "VND" },
      { key: "roas", label: "ROAS", direction: "maximize", unit: "ratio" },
      { key: "mer", label: "MER toàn mảng", direction: "maximize", unit: "ratio" },
      { key: "profit_after_ads", label: "Lợi nhuận sau quảng cáo", direction: "maximize", unit: "VND" },
      { key: "channel_contribution_margin", label: "Contribution margin theo kênh", direction: "maximize", unit: "%" },
    ],
    allowedActions: [
      "sync_pancake_ads_metrics",
      "rank_channels",
      "rank_campaigns",
      "detect_metric_anomaly",
      "recommend_budget_change",
      "recommend_creative_rotation",
      "recommend_scale_hold_kill"
    ],
    approvalRequiredFor: ["spend_money", "launch_campaign", "scale_campaign"],
    riskLevel: "high",
  },
  {
    id: "sales-funnel-analyst",
    name: "AI Sales Funnel Analyst",
    department: "crm",
    mission: "Đọc dữ liệu Pancake, Botcake và Pancake CRM để đo conversion từng tầng; không trực Page và không thay hệ thống chốt khách.",
    inputs: ["Pancake conversations", "Botcake events", "Pancake CRM", "appointments", "orders", "campaign source"],
    outputs: ["funnel conversion", "staff/system bottleneck", "source quality", "follow-up risk"],
    kpis: [
      { key: "message_to_data", label: "Tin nhắn → Data", direction: "maximize", unit: "%" },
      { key: "data_to_appointment", label: "Data → Hẹn", direction: "maximize", unit: "%" },
      { key: "appointment_to_arrival", label: "Hẹn → Đến", direction: "maximize", unit: "%" },
      { key: "data_to_order", label: "Data → Đơn", direction: "maximize", unit: "%" },
    ],
    allowedActions: ["analyze_funnel", "flag_conversion_drop", "attribute_source_quality"],
    approvalRequiredFor: [],
    riskLevel: "low",
  },
  {
    id: "operations-controller",
    name: "AI Operations Controller",
    department: "operations",
    mission: "Theo dõi tồn kho, fulfillment, SLA, giao hàng và hoàn hủy để cảnh báo thất thoát trước khi ảnh hưởng lợi nhuận.",
    inputs: ["inventory", "orders", "shipping", "supplier SLA", "QC data"],
    outputs: ["reorder alerts", "stock risk", "fulfillment exceptions", "supplier performance"],
    kpis: [
      { key: "return_rate", label: "Hoàn/hủy", direction: "minimize", unit: "%" },
      { key: "stock_days", label: "Ngày tồn kho", direction: "minimize", unit: "days" },
      { key: "on_time", label: "Giao đúng hạn", direction: "maximize", unit: "%" },
    ],
    allowedActions: ["flag_stockout", "recommend_reorder", "open_exception"],
    approvalRequiredFor: ["place_purchase_order", "change_supplier"],
    riskLevel: "high",
  },
  {
    id: "finance-controller",
    name: "AI Finance Controller",
    department: "finance",
    mission: "Tính lợi nhuận thật, dòng tiền và ngưỡng an toàn của từng mảng trước mọi đề xuất scale.",
    inputs: ["revenue", "COGS", "ad spend", "fees", "payroll", "tax", "returns"],
    outputs: ["P&L", "cash forecast", "profit alerts", "break-even analysis"],
    kpis: [
      { key: "net_profit", label: "Lợi nhuận ròng", direction: "maximize", unit: "VND" },
      { key: "net_margin", label: "Biên ròng", direction: "maximize", unit: "%" },
      { key: "cash_buffer", label: "Quỹ tiền mặt", direction: "maximize", unit: "VND" },
    ],
    allowedActions: ["calculate_pnl", "forecast_cash", "flag_margin_risk"],
    approvalRequiredFor: ["move_cash", "change_tax_or_legal_policy"],
    riskLevel: "critical",
  },
  {
    id: "compliance-guardian",
    name: "AI Compliance Guardian",
    department: "compliance",
    mission: "Cảnh báo rủi ro pháp lý, thuế, quảng cáo, dữ liệu và claim sản phẩm trước khi thành sự cố.",
    inputs: ["contracts", "invoices", "product claims", "tax rules", "privacy rules"],
    outputs: ["risk flags", "required approvals", "compliance checklist"],
    kpis: [
      { key: "critical_incidents", label: "Sự cố nghiêm trọng", direction: "minimize", unit: "count" },
    ],
    allowedActions: ["block_workflow", "require_approval", "request_document"],
    approvalRequiredFor: ["change_tax_or_legal_policy", "publish_sensitive_claim"],
    riskLevel: "critical",
  },
  {
    id: "anomaly-early-warning",
    name: "AI Anomaly & Early Warning",
    department: "analytics",
    mission: "Theo dõi chuỗi thời gian của mọi KPI, phát hiện bất thường, dự báo vượt ngưỡng và kích hoạt phân tích nguyên nhân gốc.",
    inputs: ["metric time series", "baselines", "business targets", "seasonality", "alerts history"],
    outputs: ["anomaly alerts", "forecast threshold breach", "root-cause request", "estimated financial impact"],
    kpis: [
      { key: "false_positive_rate", label: "Tỷ lệ cảnh báo sai", direction: "minimize", unit: "%" },
      { key: "warning_lead_time", label: "Thời gian cảnh báo trước", direction: "maximize", unit: "days" },
    ],
    allowedActions: ["detect_anomaly", "forecast_metric", "trigger_root_cause_analysis"],
    approvalRequiredFor: [],
    riskLevel: "low",
  },
];

export const aiCompanyAgentById = new Map(aiCompanyAgents.map((agent) => [agent.id, agent]));
