import { AICompanyAgent } from "./types";

export const aiCompanyAgents: AICompanyAgent[] = [
  {
    id: "chief-commercial-officer",
    name: "AI Chief Commercial Officer",
    department: "executive",
    mission: "Tối đa hóa lợi nhuận sau thuế và tốc độ quay vòng vốn trên toàn bộ danh mục kinh doanh.",
    inputs: ["P&L", "cashflow", "inventory", "ad performance", "CRM", "supplier data"],
    outputs: ["capital allocation", "portfolio priorities", "scale/kill decisions"],
    kpis: [
      { key: "net_margin", label: "Biên lợi nhuận ròng", direction: "maximize", unit: "%" },
      { key: "cash_conversion", label: "Chu kỳ chuyển đổi tiền", direction: "minimize", unit: "days" },
      { key: "roic", label: "ROIC", direction: "maximize", unit: "%" },
    ],
    allowedActions: ["recommend_budget", "rank_business_units", "request_analysis"],
    approvalRequiredFor: ["move_cash", "sign_contract", "scale_campaign"],
    riskLevel: "critical",
  },
  {
    id: "deal-scout",
    name: "AI Deal Scout",
    department: "deal",
    mission: "Tìm nhà sản xuất, xưởng, chủ sản phẩm và deal hợp tác có năng lực sản xuất tốt nhưng thương mại hóa yếu.",
    inputs: ["supplier profiles", "market signals", "unit economics", "capacity", "legal documents"],
    outputs: ["deal shortlist", "partner score", "due diligence checklist"],
    kpis: [
      { key: "qualified_deals", label: "Deal đạt chuẩn", direction: "maximize", unit: "count" },
      { key: "deal_margin", label: "Biên tiềm năng", direction: "maximize", unit: "%" },
    ],
    allowedActions: ["score_partner", "prepare_due_diligence", "draft_deal_structure"],
    approvalRequiredFor: ["sign_contract"],
    riskLevel: "high",
  },
  {
    id: "product-strategist",
    name: "AI Product Strategist",
    department: "product",
    mission: "Chọn SKU, cấu trúc offer, giá bán và test plan dựa trên unit economics thay vì cảm tính.",
    inputs: ["product cost", "competitors", "customer demand", "return rate", "gross margin"],
    outputs: ["SKU score", "pricing", "offer", "test budget"],
    kpis: [
      { key: "contribution_margin", label: "Contribution margin", direction: "maximize", unit: "%" },
      { key: "test_payback", label: "Thời gian hoàn vốn test", direction: "minimize", unit: "days" },
    ],
    allowedActions: ["recommend_price", "design_offer", "create_test_plan"],
    approvalRequiredFor: ["change_price", "launch_campaign"],
    riskLevel: "high",
  },
  {
    id: "brand-director",
    name: "AI Brand Director",
    department: "brand",
    mission: "Biến hàng hóa thành thương hiệu có định vị, tài sản sáng tạo và lý do mua rõ ràng.",
    inputs: ["brand strategy", "customer segments", "creative library", "competitor positioning"],
    outputs: ["positioning", "creative briefs", "brand guidelines", "content angles"],
    kpis: [
      { key: "creative_win_rate", label: "Tỷ lệ creative thắng", direction: "maximize", unit: "%" },
      { key: "brand_search", label: "Tăng tìm kiếm thương hiệu", direction: "maximize", unit: "%" },
    ],
    allowedActions: ["generate_brief", "score_creative", "recommend_positioning"],
    approvalRequiredFor: ["publish_sensitive_claim"],
    riskLevel: "medium",
  },
  {
    id: "growth-operator",
    name: "AI Growth Operator",
    department: "growth",
    mission: "Điều hành test, tối ưu và scale quảng cáo theo lợi nhuận đóng góp và chất lượng khách hàng.",
    inputs: ["Meta Ads", "TikTok Ads", "Google Ads", "orders", "CRM", "returns"],
    outputs: ["budget moves", "creative rotation", "audience tests", "scale recommendations"],
    kpis: [
      { key: "cac", label: "CAC đơn giao thành công", direction: "minimize", unit: "VND" },
      { key: "mer", label: "MER", direction: "maximize", unit: "ratio" },
      { key: "profit_after_ads", label: "Lợi nhuận sau ads", direction: "maximize", unit: "VND" },
    ],
    allowedActions: ["pause_ad", "recommend_budget_change", "create_ab_test"],
    approvalRequiredFor: ["spend_money", "launch_campaign", "scale_campaign"],
    riskLevel: "critical",
  },
  {
    id: "sales-crm-manager",
    name: "AI Sales & CRM Manager",
    department: "crm",
    mission: "Tăng conversion, mua lại và LTV bằng CRM, follow-up và phân nhóm khách hàng tự động.",
    inputs: ["messages", "orders", "customer profile", "support history", "campaign source"],
    outputs: ["lead score", "next best action", "segments", "retention workflows"],
    kpis: [
      { key: "conversion", label: "Tỷ lệ chuyển đổi", direction: "maximize", unit: "%" },
      { key: "repeat_rate", label: "Tỷ lệ mua lại", direction: "maximize", unit: "%" },
      { key: "ltv", label: "LTV", direction: "maximize", unit: "VND" },
    ],
    allowedActions: ["score_customer", "trigger_followup", "recommend_offer"],
    approvalRequiredFor: ["issue_refund"],
    riskLevel: "medium",
  },
  {
    id: "operations-controller",
    name: "AI Operations Controller",
    department: "operations",
    mission: "Theo dõi tồn kho, fulfillment, SLA và chất lượng để giảm tiền chết và hoàn hủy.",
    inputs: ["inventory", "orders", "shipping", "supplier SLA", "QC data"],
    outputs: ["reorder alerts", "stock risk", "fulfillment exceptions", "supplier score"],
    kpis: [
      { key: "return_rate", label: "Hoàn/hủy", direction: "minimize", unit: "%" },
      { key: "stock_days", label: "Ngày tồn kho", direction: "minimize", unit: "days" },
      { key: "on_time", label: "Giao đúng hạn", direction: "maximize", unit: "%" },
    ],
    allowedActions: ["flag_stockout", "recommend_reorder", "open_exception"],
    approvalRequiredFor: ["place_purchase_order", "change_supplier"],
    riskLevel: "high",
  },
  {
    id: "finance-controller",
    name: "AI Finance Controller",
    department: "finance",
    mission: "Tính lợi nhuận thật, dòng tiền và ngưỡng an toàn trước mọi quyết định scale.",
    inputs: ["revenue", "COGS", "ad spend", "fees", "payroll", "tax", "returns"],
    outputs: ["P&L", "cash forecast", "profit alerts", "break-even analysis"],
    kpis: [
      { key: "net_profit", label: "Lợi nhuận ròng", direction: "maximize", unit: "VND" },
      { key: "net_margin", label: "Biên ròng", direction: "maximize", unit: "%" },
      { key: "cash_buffer", label: "Quỹ tiền mặt", direction: "maximize", unit: "VND" },
    ],
    allowedActions: ["calculate_pnl", "forecast_cash", "flag_margin_risk"],
    approvalRequiredFor: ["move_cash", "change_tax_or_legal_policy"],
    riskLevel: "critical",
  },
  {
    id: "compliance-guardian",
    name: "AI Compliance Guardian",
    department: "compliance",
    mission: "Chặn quyết định có rủi ro pháp lý, thuế, quảng cáo, dữ liệu hoặc cam kết sản phẩm.",
    inputs: ["contracts", "invoices", "product claims", "tax rules", "privacy rules"],
    outputs: ["risk flags", "required approvals", "compliance checklist"],
    kpis: [
      { key: "critical_incidents", label: "Sự cố nghiêm trọng", direction: "minimize", unit: "count" },
    ],
    allowedActions: ["block_workflow", "require_approval", "request_document"],
    approvalRequiredFor: ["change_tax_or_legal_policy", "publish_sensitive_claim"],
    riskLevel: "critical",
  },
  {
    id: "business-analyst",
    name: "AI Business Analyst",
    department: "analytics",
    mission: "Giải thích vì sao doanh thu, lợi nhuận, CAC, conversion hoặc hoàn hủy thay đổi và đề xuất hành động.",
    inputs: ["warehouse", "CRM", "ad data", "orders", "finance"],
    outputs: ["daily brief", "root-cause analysis", "scenario model", "recommendations"],
    kpis: [
      { key: "decision_accuracy", label: "Độ chính xác khuyến nghị", direction: "maximize", unit: "%" },
    ],
    allowedActions: ["query_metrics", "generate_report", "run_scenario"],
    approvalRequiredFor: [],
    riskLevel: "low",
  },
];

export const aiCompanyAgentById = new Map(aiCompanyAgents.map((agent) => [agent.id, agent]));
