#!/usr/bin/env bash
set -euo pipefail

# ══════════════════════════════════════════════════════════════
# eMarketer CRM Instance Deployer
# Usage: ./deploy-instance.sh <payload.json>
#
# Payload JSON:
# {
#   "orderId": "...",
#   "workspaceId": "...",
#   "instanceId": "...",
#   "productKey": "CRM_SPA_PRO",
#   "imageRef": "registry.emk.vn/crm-spa:v1.0.0",
#   "planKey": "MONTHLY",
#   "addons": ["AI_ASSISTANT", "AUTOMATION"],
#   "domain": "crm.congtykhach.com",
#   "adminEmail": "admin@congtykhach.com",
#   "businessName": "Công Ty Khách",
#   "callbackUrl": "https://hub.emarketervietnam.vn/api/hub/deploy/callback",
#   "callbackSecret": "..."
# }
#
# Idempotent: if instance dir already exists, skip or update.
# ══════════════════════════════════════════════════════════════

PAYLOAD_FILE="${1:?Usage: $0 <payload.json>}"

# Parse JSON payload
ORDER_ID=$(jq -r '.orderId' "$PAYLOAD_FILE")
WORKSPACE_ID=$(jq -r '.workspaceId' "$PAYLOAD_FILE")
INSTANCE_ID=$(jq -r '.instanceId' "$PAYLOAD_FILE")
PRODUCT_KEY=$(jq -r '.productKey' "$PAYLOAD_FILE")
IMAGE_REF=$(jq -r '.imageRef' "$PAYLOAD_FILE")
PLAN_KEY=$(jq -r '.planKey' "$PAYLOAD_FILE")
DOMAIN=$(jq -r '.domain' "$PAYLOAD_FILE")
ADMIN_EMAIL=$(jq -r '.adminEmail' "$PAYLOAD_FILE")
BUSINESS_NAME=$(jq -r '.businessName' "$PAYLOAD_FILE")
CALLBACK_URL=$(jq -r '.callbackUrl' "$PAYLOAD_FILE")
CALLBACK_SECRET=$(jq -r '.callbackSecret' "$PAYLOAD_FILE")

# ── Directory convention ──────────────────────────────────────
# /opt/emk/instances/<workspaceId>/<productKey>/
INSTANCE_DIR="/opt/emk/instances/${WORKSPACE_ID}/${PRODUCT_KEY}"
LOG_FILE="${INSTANCE_DIR}/deploy.log"

echo "══ eMarketer Deployer ═══════════════════"
echo "  Order:     ${ORDER_ID}"
echo "  Workspace: ${WORKSPACE_ID}"
echo "  Product:   ${PRODUCT_KEY}"
echo "  Image:     ${IMAGE_REF}"
echo "  Domain:    ${DOMAIN}"
echo "  Plan:      ${PLAN_KEY}"
echo "═════════════════════════════════════════"

# ── Idempotency check ─────────────────────────────────────────
if [ -f "${INSTANCE_DIR}/.deployed" ]; then
    PREV_ORDER=$(cat "${INSTANCE_DIR}/.deployed" 2>/dev/null || echo "")
    if [ "$PREV_ORDER" = "$ORDER_ID" ]; then
        echo "⚠️  Instance already deployed for this order. Skipping."
        exit 0
    fi
    echo "⚠️  Instance exists for different order. Updating..."
fi

# ── Step 1: Create instance directory ─────────────────────────
mkdir -p "${INSTANCE_DIR}"
echo "[$(date -Iseconds)] Deploy started for order=${ORDER_ID}" | tee -a "$LOG_FILE"

# ── Step 2: Pull Docker image ─────────────────────────────────
echo "🐳 Pulling image: ${IMAGE_REF}..."
docker pull "${IMAGE_REF}" 2>&1 | tee -a "$LOG_FILE"

# ── Step 3: Create DB ─────────────────────────────────────────
WS_SHORT="${WORKSPACE_ID//-/_}"
WS_SHORT="${WS_SHORT:0:20}"
DB_NAME="crm_${WS_SHORT}"
DB_USER="crm_user_${WS_SHORT}"
DB_PASS=$(openssl rand -hex 16)

echo "🗄 Creating database: ${DB_NAME}..."
sudo -u postgres createdb "${DB_NAME}" 2>/dev/null || echo "DB already exists"
sudo -u postgres psql -c "
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_USER}') THEN
            CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASS}';
        END IF;
    END
    \$\$;
    GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
" 2>&1 | tee -a "$LOG_FILE"

# ── Step 4: Generate secrets ──────────────────────────────────
JWT_SECRET=$(openssl rand -hex 32)
WORKSPACE_SECRET=$(openssl rand -hex 16)
ADMIN_PASS=$(openssl rand -base64 12 | tr -d '=/+' | head -c 12)

# ── Step 5: Render .env ───────────────────────────────────────
cat > "${INSTANCE_DIR}/.env" << ENVEOF
# Auto-generated by eMarketer Deployer — DO NOT EDIT
DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}
HUB_API=https://hub.emarketervietnam.vn
WORKSPACE_ID=${WORKSPACE_ID}
INSTANCE_ID=${INSTANCE_ID}
ENTITLEMENT_SECRET=${WORKSPACE_SECRET}
DOMAIN=${DOMAIN}
JWT_SECRET=${JWT_SECRET}
JWT_AUD=${DOMAIN}
NODE_ENV=production
PORT=0
PRODUCT_KEY=${PRODUCT_KEY}
PLAN_KEY=${PLAN_KEY}
ENVEOF

echo "📝 .env rendered" | tee -a "$LOG_FILE"

# ── Step 6: Docker compose ────────────────────────────────────
# Allocate random port
PORT=$(shuf -i 10000-60000 -n 1)
CONTAINER_NAME="emk-${PRODUCT_KEY,,}-${WS_SHORT}"

cat > "${INSTANCE_DIR}/docker-compose.yml" << COMPEOF
version: '3.8'
services:
  app:
    image: ${IMAGE_REF}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=${PORT}
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
COMPEOF

echo "🚀 Starting container on port ${PORT}..."
cd "${INSTANCE_DIR}"
docker compose up -d 2>&1 | tee -a "$LOG_FILE"

# ── Step 7: Run migrations + seed admin ───────────────────────
echo "🔧 Running migrations..."
sleep 5  # Wait for container to start
docker exec "${CONTAINER_NAME}" npx prisma migrate deploy 2>&1 | tee -a "$LOG_FILE" || true

echo "👤 Seeding admin user..."
docker exec "${CONTAINER_NAME}" node -e "
    const { PrismaClient } = require('@prisma/client');
    const bcrypt = require('bcryptjs');
    (async () => {
        const db = new PrismaClient();
        const hash = await bcrypt.hash('${ADMIN_PASS}', 12);
        await db.user.upsert({
            where: { email: '${ADMIN_EMAIL}' },
            create: { name: '${BUSINESS_NAME} Admin', email: '${ADMIN_EMAIL}', phone: '', password: hash, isAdmin: true, status: 'ACTIVE' },
            update: { password: hash, isAdmin: true },
        });
        console.log('Admin seeded OK');
        await db.\$disconnect();
    })();
" 2>&1 | tee -a "$LOG_FILE"

# ── Step 8: Configure reverse proxy + SSL ─────────────────────
NGINX_CONF="/etc/nginx/sites-available/${DOMAIN}"
cat > "${NGINX_CONF}" << NGXEOF
server {
    listen 80;
    server_name ${DOMAIN};

    location / {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
}
NGXEOF

ln -sf "${NGINX_CONF}" "/etc/nginx/sites-enabled/${DOMAIN}" 2>/dev/null || true
nginx -t && nginx -s reload 2>&1 | tee -a "$LOG_FILE"

# SSL — only if DNS is already pointing to us
echo "🔐 Attempting SSL..."
certbot certonly --nginx -d "${DOMAIN}" --non-interactive --agree-tos --email admin@emarketervietnam.vn 2>&1 | tee -a "$LOG_FILE" || {
    echo "⚠️  SSL failed (DNS may not be pointing here yet). Will retry later."
}

# ── Step 9: Health check ──────────────────────────────────────
echo "🏥 Health check..."
for i in {1..10}; do
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:${PORT}/api/health" 2>/dev/null || echo "000")
    if [ "$HTTP_CODE" = "200" ]; then
        echo "✅ Health check passed!" | tee -a "$LOG_FILE"
        break
    fi
    echo "  Attempt ${i}/10 — status ${HTTP_CODE}, waiting..." | tee -a "$LOG_FILE"
    sleep 3
done

# ── Step 10: Callback to Hub ──────────────────────────────────
CRM_URL="https://${DOMAIN}"
echo "📡 Calling back to Hub..."
CALLBACK_RESPONSE=$(curl -s -X POST "${CALLBACK_URL}" \
    -H "Authorization: Bearer ${CALLBACK_SECRET}" \
    -H "Content-Type: application/json" \
    -d "{
        \"instanceId\": \"${INSTANCE_ID}\",
        \"status\": \"DONE\",
        \"crmUrl\": \"${CRM_URL}\",
        \"port\": ${PORT},
        \"containerName\": \"${CONTAINER_NAME}\",
        \"adminEmail\": \"${ADMIN_EMAIL}\",
        \"adminPassword\": \"${ADMIN_PASS}\"
    }" 2>&1)

echo "Callback response: ${CALLBACK_RESPONSE}" | tee -a "$LOG_FILE"

# ── Mark as deployed (idempotency) ────────────────────────────
echo "${ORDER_ID}" > "${INSTANCE_DIR}/.deployed"

echo ""
echo "══ Deploy Complete ════════════════════════"
echo "  URL:       ${CRM_URL}"
echo "  Admin:     ${ADMIN_EMAIL}"
echo "  Password:  ${ADMIN_PASS}"
echo "  Container: ${CONTAINER_NAME}"
echo "  Port:      ${PORT}"
echo "  DB:        ${DB_NAME}"
echo "═══════════════════════════════════════════"
echo "[$(date -Iseconds)] Deploy completed successfully" | tee -a "$LOG_FILE"
