#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# deploy-crm.sh — Auto-deploy CRM instance on VPS
# Called by deployer-server.js after DNS verification
#
# Usage: ./deploy-crm.sh <domain> <instance_id> <db_name> <workspace_id> <admin_email> <hub_callback_url>
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

DOMAIN="$1"
INSTANCE_ID="$2"
DB_NAME="$3"
WORKSPACE_ID="$4"
ADMIN_EMAIL="${5:-admin@${DOMAIN}}"
HUB_CALLBACK_URL="${6:-http://localhost:3000/api/hub/deploy/callback}"

LOG_FILE="/var/log/emk-deployer.log"
DEPLOY_SECRET="${DEPLOY_CALLBACK_SECRET:-deploy-secret-key}"
CRM_BASE_DIR="/var/www/crm-instances"
NGINX_SITES="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"; }
fail() {
    log "FAILED: $*"
    # Callback to Hub with failure
    curl -sf -X POST "$HUB_CALLBACK_URL" \
        -H "Authorization: Bearer $DEPLOY_SECRET" \
        -H "Content-Type: application/json" \
        -d "{\"instanceId\":\"$INSTANCE_ID\",\"status\":\"FAILED\",\"error\":\"$*\"}" || true
    exit 1
}

log "═══════════════════════════════════════════"
log "Deploying CRM: $DOMAIN (instance: $INSTANCE_ID)"
log "DB: $DB_NAME | Workspace: $WORKSPACE_ID"
log "═══════════════════════════════════════════"

# ── 1. Validate ──────────────────────────────────────────────
[[ -z "$DOMAIN" ]] && fail "Domain is required"
[[ -z "$INSTANCE_ID" ]] && fail "Instance ID is required"
[[ -z "$DB_NAME" ]] && fail "DB name is required"

# ── 2. Create database ──────────────────────────────────────
log "Step 1/6: Creating database $DB_NAME..."
if sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
    log "  Database $DB_NAME already exists, skipping"
else
    sudo -u postgres createdb "$DB_NAME" -O postgres || fail "Failed to create database $DB_NAME"
    log "  Database $DB_NAME created"
fi

DB_URL="postgresql://postgres:postgres@localhost:5432/$DB_NAME"

# ── 3. Setup CRM instance directory ─────────────────────────
log "Step 2/6: Setting up CRM instance directory..."
INSTANCE_DIR="$CRM_BASE_DIR/$DOMAIN"
mkdir -p "$INSTANCE_DIR"

# Generate .env for the CRM instance
cat > "$INSTANCE_DIR/.env" <<EOF
# CRM Instance: $DOMAIN
# Generated: $(date -Iseconds)
DATABASE_URL=$DB_URL
NEXT_PUBLIC_APP_URL=https://$DOMAIN
WORKSPACE_ID=$WORKSPACE_ID
INSTANCE_ID=$INSTANCE_ID
ADMIN_EMAIL=$ADMIN_EMAIL

# Hub connection
HUB_URL=https://hub.emarketervietnam.vn
ENTITLEMENT_PUBLIC_KEY=${ENTITLEMENT_PUBLIC_KEY:-}

# Runtime
NODE_ENV=production
PORT=3000
EOF

log "  .env generated at $INSTANCE_DIR/.env"

# ── 4. Docker Compose ───────────────────────────────────────
log "Step 3/6: Creating Docker Compose config..."

# Find available port (starting from 4000)
USED_PORTS=$(docker ps --format '{{.Ports}}' | grep -oP '\d+(?=->3000)' | sort -n)
PORT=4000
while echo "$USED_PORTS" | grep -qw "$PORT"; do
    PORT=$((PORT + 1))
done

cat > "$INSTANCE_DIR/docker-compose.yml" <<EOF
version: '3.8'
services:
  crm:
    image: ${CRM_DOCKER_IMAGE:-node:20-alpine}
    container_name: crm-$DOMAIN
    restart: unless-stopped
    working_dir: /app
    env_file: .env
    ports:
      - "$PORT:3000"
    volumes:
      - ./app:/app
    command: ["node", "server.js"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
EOF

log "  Docker Compose created (port: $PORT)"

# ── 5. Nginx reverse proxy + SSL ────────────────────────────
log "Step 4/6: Configuring Nginx reverse proxy..."

NGINX_CONF="$NGINX_SITES/$DOMAIN.conf"
cat > "$NGINX_CONF" <<EOF
# CRM Instance: $DOMAIN
# Auto-generated by deploy-crm.sh — $(date -Iseconds)
server {
    listen 80;
    server_name $DOMAIN;

    location / {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 86400;
    }
}
EOF

# Enable site
ln -sf "$NGINX_CONF" "$NGINX_ENABLED/$DOMAIN.conf"

# Test & reload Nginx
nginx -t || fail "Nginx config test failed for $DOMAIN"
systemctl reload nginx || fail "Nginx reload failed"
log "  Nginx configured and reloaded"

# ── 6. SSL Certificate ──────────────────────────────────────
log "Step 5/6: Requesting SSL certificate..."
if [[ -d "/etc/letsencrypt/live/$DOMAIN" ]]; then
    log "  SSL cert already exists for $DOMAIN"
else
    certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m "$ADMIN_EMAIL" --redirect \
        || log "  WARNING: SSL cert request failed (continuing without SSL)"
fi

# ── 7. Start Docker container ───────────────────────────────
log "Step 6/6: Starting Docker container..."
cd "$INSTANCE_DIR"

# For now, if no Docker image, create a simple placeholder
# In production, this would pull the actual CRM Docker image
if [[ -n "${CRM_DOCKER_IMAGE:-}" ]]; then
    docker compose up -d || fail "Docker compose failed for $DOMAIN"
    log "  Container crm-$DOMAIN started"
else
    log "  No CRM_DOCKER_IMAGE set — placeholder mode"
    log "  Instance registered but no container started"
    log "  Set CRM_DOCKER_IMAGE env var to enable full Docker deploy"
fi

# ── 8. Callback to Hub ──────────────────────────────────────
log "Calling back Hub with success..."
CRM_URL="https://$DOMAIN"
TEMP_PASSWORD=$(openssl rand -base64 12)

CALLBACK_RESPONSE=$(curl -sf -X POST "$HUB_CALLBACK_URL" \
    -H "Authorization: Bearer $DEPLOY_SECRET" \
    -H "Content-Type: application/json" \
    -d "{
        \"instanceId\": \"$INSTANCE_ID\",
        \"status\": \"DONE\",
        \"crmUrl\": \"$CRM_URL\",
        \"tempPassword\": \"$TEMP_PASSWORD\",
        \"port\": $PORT,
        \"dbName\": \"$DB_NAME\"
    }" 2>&1) || log "  WARNING: Hub callback failed: $CALLBACK_RESPONSE"

log "  Hub callback sent"

log "═══════════════════════════════════════════"
log "DEPLOY COMPLETE: $DOMAIN"
log "  URL: $CRM_URL"
log "  Port: $PORT"
log "  DB: $DB_NAME"
log "  Instance: $INSTANCE_ID"
log "═══════════════════════════════════════════"
